# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 13:55
from __future__ import unicode_literals

from django.db import migrations

def combine_names(apps, schema_editor):
    Vehicle = apps.get_model("resources", "Vehicle")
    vehicles = Vehicle.objects.select_related('manufacturer').all()
    for vehicle in vehicles:
        vehicle.name = "%s %s" % (vehicle.manufacturer.name, vehicle.name)
        vehicle.save()

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
