# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 10:26
from __future__ import unicode_literals
from django.db import migrations

from django.contrib.auth import get_user_model

def setup_firt_user(apps, schema_editor):
    User = get_user_model()
    user = User.objects.create_user("leandroc", \
            email="leandroc@inatel.br", password="inatel2016")

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20160721_1355'),
    ]

    operations = [
        migrations.RunPython(setup_firt_user),
    ]
